### GET products
GET http://localhost:3000/products HTTP/1.1
Accept: application/json

### POST create a new product
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "name": "Smartphone02",
  "description": "...",
  "price": 200,
  "reference": "002",
  "img": "http://example.com/smartphone.jpg",
  "stock": 20,
  "categoryID": "674e2931a1c1c1bd8664d6ec"
}

### PUT update product to ID
PUT http://localhost:3000/products/674e4f523ca3a8a15126cdbf HTTP/1.1
Content-Type: application/json

{
  "price": 199,
  "stock": 21
}

### DELETE product to ID
DELETE http://localhost:3000/products/674c8ffd05de7279e35ec6e8 HTTP/1.1
Accept: application/json

### --> Categories <--
### GET categories
GET http://localhost:3000/categories HTTP/1.1


### Create Category
POST http://localhost:3000/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Smartphone"
}

### GET products by category
GET http://localhost:3000/categories/674e2931a1c1c1bd8664d6ec/products/ HTTP/1.1

### DELETE category by ID
DELETE http://localhost:3000/categories/674e28c0a1c1c1bd8664d6dd HTTP/1.1
